USER_ID_SESSIONS_KEY = "user_id_sessions"

USER_ID_REQUEST_URL_NAME = 'user_id'
INSTITUTION_ID_REQUEST_URL_NAME = 'institution_id'

PERMISSION_TYPE_DOCTOR = "Doctor"
PERMISSION_TYPE_PATIENT = "Patient"
PERMISSION_TYPE_DEVELOPER = "Developer"
PERMISSION_TYPE_SUPERVISOR = "Supervisor"

INSTITUTION_HOSPITAL_ID = 1
INSTITUTION_SOFTWARE_ID = 2
INSTITUTION_LAB_ID = 3

INSTITUTION_HOSPITAL_NAME = "Hospital"
INSTITUTION_SOFTWARE_NAME = "Software Company"
INSTITUTION_LAB_NAME = "Lab"
