# Generated by Django 2.2.5 on 2019-09-19 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('logo', models.FileField(upload_to='user_type_logo')),
            ],
            managers=[
                ('types', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('second_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.FileField(blank=True, upload_to='user_photos')),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(blank=True, max_length=64)),
                ('birth_date', models.DateField()),
                ('register_date', models.DateField(auto_now=True)),
                ('is_login', models.BooleanField(blank=True, default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.UserType')),
            ],
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=64)),
                ('photo', models.FileField(blank=True, upload_to='lab_photos')),
                ('description', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(blank=True, max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=64)),
                ('photo', models.FileField(blank=True, upload_to='hospital_photos')),
                ('description', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(blank=True, max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('photo', models.FileField(blank=True, upload_to='company_photos')),
                ('logo', models.FileField(upload_to='company_logo')),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('street', models.CharField(blank=True, max_length=64)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User')),
            ],
        ),
    ]
