# Generated by Django 2.2.5 on 2019-09-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('logo', models.FileField(blank=True, upload_to='institution_type_logo')),
            ],
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='Institutions',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
