# Generated by Django 2.2.5 on 2019-09-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190920_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutions',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.InstitutionTypes'),
            preserve_default=False,
        ),
    ]
