# Generated by Django 2.2.5 on 2019-09-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_institutions_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('photo', models.FileField(blank=True, upload_to='company_photos')),
                ('logo', models.FileField(upload_to='company_logo')),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('street', models.CharField(blank=True, max_length=64)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User')),
            ],
        ),
        migrations.RenameModel(
            old_name='InstitutionTypes',
            new_name='InstitutionType',
        ),
        migrations.DeleteModel(
            name='Institutions',
        ),
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.InstitutionType'),
        ),
    ]
