# Generated by Django 2.2.5 on 2019-09-21 12:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190920_1807'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='institution',
            managers=[
                ('Institutions', django.db.models.manager.Manager()),
            ],
        ),
    ]
