# Generated by Django 2.2.5 on 2019-10-02 22:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190928_1533'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='institution',
            managers=[
                ('institutions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone_number',
            field=models.CharField(max_length=32),
        ),
    ]
