# Generated by Django 2.2.5 on 2019-10-03 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191003_0122'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='institutiontype',
            managers=[
                ('types', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HospitalJoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_created=True)),
                ('is_accepted', models.BooleanField(blank=True, default=None)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('msg', models.CharField(blank=True, max_length=128)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Institution')),
            ],
        ),
    ]
