# Generated by Django 2.2.5 on 2019-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191003_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaljoinrequest',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
