# Generated by Django 2.2.5 on 2019-10-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191004_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaljoinrequest',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
