# Generated by Django 2.2.5 on 2019-10-07 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_report_reporthub_reportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
