# Generated by Django 2.2.5 on 2019-10-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_report_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutiontype',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='logo',
        ),
    ]
