# Generated by Django 2.2.5 on 2019-10-08 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191009_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthub',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
