# Generated by Django 2.2.5 on 2019-10-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191015_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('method', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='IOAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('is_input', models.BooleanField()),
                ('json_name', models.CharField(max_length=128)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.API')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(max_length=128, upload_to='')),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=64)),
                ('logo', models.FileField(upload_to='F114225')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.API')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='ModelSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_numbers', models.IntegerField(blank=True)),
                ('is_free', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='F123354')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Model')),
            ],
        ),
        migrations.CreateModel(
            name='IORequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_value', models.FileField(upload_to='F854634')),
                ('text_value', models.TextField()),
                ('io', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IOAPI')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ModelRequest')),
            ],
        ),
    ]
