# Generated by Django 2.2.5 on 2019-10-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_api_ioapi_iorequest_model_modelimage_modelrequest_modelsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='request_cost',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
