# Generated by Django 2.2.5 on 2019-10-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_model_request_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioapi',
            name='is_file',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
