# Generated by Django 2.2.5 on 2019-10-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_ioapi_is_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
