# Generated by Django 2.2.5 on 2019-10-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191021_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsubscription',
            name='model',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.Model'),
            preserve_default=False,
        ),
    ]
