# Generated by Django 2.2.5 on 2019-10-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_modelsubscription_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsubscription',
            name='model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Model'),
        ),
    ]
