# Generated by Django 2.2.5 on 2019-10-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191022_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsubscription',
            name='model',
        ),
    ]
