# Generated by Django 2.2.5 on 2019-10-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_modelsubscription_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='free_request',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
