# Generated by Django 2.2.5 on 2019-10-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20191022_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='free_request',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
