# Generated by Django 2.2.5 on 2019-10-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20191022_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='doctor_model',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='lab_model',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='patient_model',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
