# Generated by Django 2.2.5 on 2019-10-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20191023_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='price_sell',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='sell_request_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
