# Generated by Django 2.2.5 on 2019-10-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20191027_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='price_sell',
            new_name='discount_percentage',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='sell_request_number',
            new_name='discount_rate',
        ),
        migrations.RenameField(
            model_name='modelsubscription',
            old_name='request_numbers',
            new_name='number_of_request',
        ),
        migrations.AddField(
            model_name='modelsubscription',
            name='request_used',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
