# Generated by Django 2.2.5 on 2019-10-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20191027_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsubscription',
            name='request_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
