# Generated by Django 2.2.5 on 2019-10-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20191027_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iorequest',
            name='file_value',
            field=models.FileField(blank=True, null=True, upload_to='F854634'),
        ),
        migrations.AlterField(
            model_name='iorequest',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
