# Generated by Django 2.2.5 on 2019-10-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20191030_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthub',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_hub_instance', to='app.Report'),
        ),
    ]
