# Generated by Django 2.2.5 on 2019-10-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20191030_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='serial_numbers',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
