# Generated by Django 2.2.5 on 2019-10-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_report_serial_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='serial_numbers',
            field=models.CharField(max_length=9),
        ),
    ]
