# Generated by Django 2.2.5 on 2019-10-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20191030_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='serial_numbers',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
