# Generated by Django 2.2.5 on 2019-11-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20191030_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('count', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
